/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.109
 * Generated at: 2026-06-11 14:38:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    String erro = (String) request.getAttribute("erro");
    String sucesso = (String) request.getAttribute("sucesso");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"pt-BR\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Login - FindGo</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        html {\r\n");
      out.write("            scroll-behavior: smooth;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            font-family: 'Inter', 'Segoe UI', sans-serif;\r\n");
      out.write("            background: linear-gradient(135deg, #8b6f47 0%, #5d4037 50%, #3e2723 100%);\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            overflow-x: hidden;\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body::before {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            width: 400px;\r\n");
      out.write("            height: 400px;\r\n");
      out.write("            background: rgba(212, 165, 116, 0.1);\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            top: -100px;\r\n");
      out.write("            left: -100px;\r\n");
      out.write("            animation: float 6s ease-in-out infinite;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body::after {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            width: 300px;\r\n");
      out.write("            height: 300px;\r\n");
      out.write("            background: rgba(139, 111, 71, 0.1);\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            bottom: -50px;\r\n");
      out.write("            right: -50px;\r\n");
      out.write("            animation: float 8s ease-in-out infinite reverse;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes float {\r\n");
      out.write("            0%, 100% { transform: translateY(0px); }\r\n");
      out.write("            50% { transform: translateY(20px); }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-container {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            z-index: 10;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            max-width: 420px;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-card {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.95);\r\n");
      out.write("            backdrop-filter: blur(20px);\r\n");
      out.write("            -webkit-backdrop-filter: blur(20px);\r\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.2);\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            padding: 50px 40px;\r\n");
      out.write("            box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);\r\n");
      out.write("            animation: slideUp 0.6s ease-out;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes slideUp {\r\n");
      out.write("            from {\r\n");
      out.write("                opacity: 0;\r\n");
      out.write("                transform: translateY(30px);\r\n");
      out.write("            }\r\n");
      out.write("            to {\r\n");
      out.write("                opacity: 1;\r\n");
      out.write("                transform: translateY(0);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-header {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-bottom: 40px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logo {\r\n");
      out.write("            font-size: 3rem;\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-header h1 {\r\n");
      out.write("            font-size: 28px;\r\n");
      out.write("            color: #5d4037;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            margin-bottom: 8px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-header p {\r\n");
      out.write("            color: #8b6f47;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .alert {\r\n");
      out.write("            padding: 12px 16px;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            animation: slideDown 0.3s ease-out;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .alert-error {\r\n");
      out.write("            background: #fee2e2;\r\n");
      out.write("            color: #dc2626;\r\n");
      out.write("            border: 1px solid #fca5a5;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .alert-success {\r\n");
      out.write("            background: #dcfce7;\r\n");
      out.write("            color: #059669;\r\n");
      out.write("            border: 1px solid #86efac;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes slideDown {\r\n");
      out.write("            from {\r\n");
      out.write("                opacity: 0;\r\n");
      out.write("                transform: translateY(-10px);\r\n");
      out.write("            }\r\n");
      out.write("            to {\r\n");
      out.write("                opacity: 1;\r\n");
      out.write("                transform: translateY(0);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group {\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        label {\r\n");
      out.write("            display: block;\r\n");
      out.write("            margin-bottom: 8px;\r\n");
      out.write("            color: #5d4037;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        input[type=\"email\"],\r\n");
      out.write("        input[type=\"password\"] {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 12px 16px;\r\n");
      out.write("            border: 2px solid #e0d5c7;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            font-family: inherit;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            background: #fafaf8;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        input[type=\"email\"]:focus,\r\n");
      out.write("        input[type=\"password\"]:focus {\r\n");
      out.write("            outline: none;\r\n");
      out.write("            border-color: #d4a574;\r\n");
      out.write("            background: #fff;\r\n");
      out.write("            box-shadow: 0 0 0 3px rgba(212, 165, 116, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .remember-forgot {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            margin-bottom: 25px;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .remember-forgot label {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            color: #5d4037;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .remember-forgot input[type=\"checkbox\"] {\r\n");
      out.write("            margin-right: 6px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            accent-color: #8b6f47;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .remember-forgot a {\r\n");
      out.write("            color: #8b6f47;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            transition: color 0.3s ease;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .remember-forgot a:hover {\r\n");
      out.write("            color: #d4a574;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-btn {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 13px;\r\n");
      out.write("            background: linear-gradient(135deg, #8b6f47 0%, #d4a574 100%);\r\n");
      out.write("            color: white;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            box-shadow: 0 8px 20px rgba(139, 111, 71, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-btn:hover {\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("            box-shadow: 0 12px 30px rgba(139, 111, 71, 0.4);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-btn:active {\r\n");
      out.write("            transform: translateY(0);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .signup-link {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: #8b6f47;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            margin-top: 25px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .signup-link a {\r\n");
      out.write("            color: #d4a574;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            transition: color 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .signup-link a:hover {\r\n");
      out.write("            color: #8b6f47;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @media (max-width: 480px) {\r\n");
      out.write("            .login-card {\r\n");
      out.write("                padding: 40px 25px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .login-header h1 {\r\n");
      out.write("                font-size: 24px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .logo {\r\n");
      out.write("                font-size: 2.5rem;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"login-container\">\r\n");
      out.write("        <div class=\"login-card\">\r\n");
      out.write("            <div class=\"login-header\">\r\n");
      out.write("                <div class=\"logo\"><i class=\"fas fa-location-arrow\"></i></div>\r\n");
      out.write("                <h1>FindGo</h1>\r\n");
      out.write("                <p>Encontre e compartilhe seus itens</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            ");
 if (erro != null) { 
      out.write("\r\n");
      out.write("                <div class=\"alert alert-error\">\r\n");
      out.write("                    <i class=\"fas fa-exclamation-circle\"></i> ");
      out.print( erro );
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("            ");
 if (sucesso != null) { 
      out.write("\r\n");
      out.write("                <div class=\"alert alert-success\">\r\n");
      out.write("                    <i class=\"fas fa-check-circle\"></i> ");
      out.print( sucesso );
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\" method=\"POST\">\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"email\">Email</label>\r\n");
      out.write("                    <input type=\"email\" id=\"email\" name=\"email\" placeholder=\"seu@email.com\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"password\">Senha</label>\r\n");
      out.write("                    <input type=\"password\" id=\"password\" name=\"senha\" placeholder=\"Digite sua senha\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"remember-forgot\">\r\n");
      out.write("                    <label>\r\n");
      out.write("                        <input type=\"checkbox\" name=\"remember\">\r\n");
      out.write("                        Lembrar de mim\r\n");
      out.write("                    </label>\r\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/esqueceu-senha.jsp\">Esqueceu a senha?</a>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <button type=\"submit\" class=\"login-btn\">\r\n");
      out.write("                    <i class=\"fas fa-sign-in-alt\"></i> Entrar\r\n");
      out.write("                </button>\r\n");
      out.write("            </form>\r\n");
      out.write("\r\n");
      out.write("            <p class=\"signup-link\">\r\n");
      out.write("                Não tem conta? <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/signup.jsp\">Criar conta</a>\r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        const emailInput = document.getElementById('email');\r\n");
      out.write("        const rememberCheckbox = document.querySelector('input[name=\"remember\"]');\r\n");
      out.write("\r\n");
      out.write("        const savedEmail = localStorage.getItem('userEmail');\r\n");
      out.write("        if (savedEmail) {\r\n");
      out.write("            emailInput.value = savedEmail;\r\n");
      out.write("            rememberCheckbox.checked = true;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        rememberCheckbox.addEventListener('change', function() {\r\n");
      out.write("            if (this.checked) {\r\n");
      out.write("                localStorage.setItem('userEmail', emailInput.value);\r\n");
      out.write("            } else {\r\n");
      out.write("                localStorage.removeItem('userEmail');\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        emailInput.addEventListener('change', function() {\r\n");
      out.write("            if (rememberCheckbox.checked) {\r\n");
      out.write("                localStorage.setItem('userEmail', this.value);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
